### ISSUE TITLE
Move repository to organization

### ISSUE THREAD

**Issue by AlexWayfer** [r18n/r18n#197]
Hi, @ai!

I suggest to move this repository to a new organization (`github.com/r18n`).

For what: I like this gem(s), and appreciate the "Collaborator" role from you, but I can't change the settings, like integrations.

I want to integrate with Cirrus CI or something else instead of Travis CI. Travis had many bugs with Ruby (system gems and Bundler). It also uses deprecated GitHub API:

![image](https://user-images.githubusercontent.com/6510020/47269910-be424b00-d56c-11e8-9cb3-4f4609d5e4b4.png)

Oh, also Depfu integration will be handful.

Some reference from another repo which was moved to organization: https://github.com/filewatcher/filewatcher/issues/90

Also gems can be splitted into different repos… but I'm not sure about this.

I can create a new organization (with you as Owner), or wait while you do this.

`/ai/r18n` will be redirected by GitHub after moving.

What do you think?

**Comment by ai** [comment]
I think it will be a good idea :+1:

**Comment by AlexWayfer** [comment]
Done: https://github.com/r18n

I'm waiting for repo transfer.

**Comment by AlexWayfer** [comment]
Awesome, thank you!
