### ISSUE TITLE
Porting to javascript

### ISSUE THREAD

**Issue by activestylus** [r18n/r18n#205]
First of all I LOVE your API. So much nicer than classic I18n.

Was just wondering how feasible it would be to access these translations via javascript.

Sort of like this: https://github.com/fnando/i18n-js

Any efforts, or at least interest on this front?

**Comment by AlexWayfer** [comment]
I'm going to close this as answered question/suggestion. Really, I still don't want to implement i18n (r18n) in JavaScript. But maybe sometimes in the future, who knows…
