### ISSUE TITLE
Change licenses to MIT or similar

### ISSUE THREAD

**Issue by AlexWayfer** [r18n/r18n#223]
Hello, @ai!

I think, our company has problems with using this library in commercial source-closed public product.

I appreciate your choice, but I'm asking you to change the license to something more free, like MIT or BSD, what will make it use more free.

What do you think?

Also, it can be handy to remove licenses as code-comments in almost each file, left them as separate file and fields in gem specs.

**Comment by AlexWayfer** [comment]
We've done some investigations:

We can use LGPL-3 library in closed-source software, but, if we want to fork and change R18n — we should public the sources.

It's OK.

But the code-comments with license repeating are annoying. :grin:

**Comment by ai** [comment]
I can grant you permission to change my choice to MIT, but you will need also ask all contributors too, which will be very hard.

**Comment by AlexWayfer** [comment]
> I can grant you permission to change my choice to MIT, but you will need also ask all contributors too, which will be very hard.

Oh, 54 other people… I saw your name in the License, and I thought it'd be enough, but if you sure that not — OK, I got it. Anyway, thank you. 

As I wrote, right now we don't see issues with LGPL-3 library, and I hope nobody will.
