### ISSUE TITLE
Error when using activesupport without rails

### ISSUE THREAD

**Issue by mybooking-es** [r18n/r18n#251]
We are using r18n in a project that uses activesupport but not rails. Since the last update it's broken when it does find a translation due to the following code. ActiveSupport::SafeBuffer is defined in the project but require 'action_view' breaks the execution.

Please, would you mind to check activesupport using a different conditions?

Filters.add(Untranslated, :untranslated_html) do |_v, _c, transl, untransl|
    if defined? ActiveSupport::SafeBuffer
      require 'action_view'
      self.class.include ActionView::Helpers::TagHelper
      transl + tag.span("[#{untransl}]", style: 'color: red')
    else
      Utils.escape_html(transl) +
        "<span style=\"color: red\">[#{Utils.escape_html(untransl)}]</span>"
    end
end

**Note** It's working fine with 4.0.0 but not with master branch.

**Comment by AlexWayfer** [comment]
Hello!

Thank you for your report.

It has been done in #250, due to [the `Rails/OutputSafety` RuboCop cop](https://github.com/rubocop-hq/rubocop-rails/blob/b330fb5/docs/modules/ROOT/pages/cops_rails.adoc#railsoutputsafety).

But [`content_tag` is from `ActionView`](https://apidock.com/rails/v6.0.0/ActionView/Helpers/TagHelper/content_tag).

I didn't know that there are projects with `ActiveSupport::SafeBuffer`, but without `ActionView`. Are you sure that we can disable this cop locally and use non-recommended method?

**Comment by mybooking-es** [comment]
Hi @AlexWayfer , I'm sorry I didn't answer before. We have a project that uses delayed_jobs with datamapper. It requires dm-active_model, and the activesupport. That's why we have a project with ActionSupport but without ActionView.
I'm not sure you can disable the cop. Could you check an ActionView class instead an ActiveSupport one?

**Comment by AlexWayfer** [comment]
> I'm not sure you can disable the cop.

I'm pretty sure this cop is about user input (preventing XSS attacks), and we can ignore it for translations (developer input with explicit `html` flag).



> Could you check an ActionView class instead an ActiveSupport one?

Sorry, I don't understand you. What is "check a class"? You has no `ActionView` in your project anyway, that was an error.

**Comment by mybooking-es** [comment]
I've been you have updated the code in your last commit. It does not include require 'action_view' and self.class.include ActionView::Helpers::TagHelper, so if a project does not use ActionView it will not fail. 

Thanks

**Comment by AlexWayfer** [comment]
> I've been you have updated the code in your last commit. It does not include require 'action_view' and self.class.include ActionView::Helpers::TagHelper, so if a project does not use ActionView it will not fail.
> 
> Thanks

Yes, that's why I've closed your issue without your response: I've decided to revert changes in prior of projects like your instead of RuboCop's satisfaction without a lot of meaning.
